# Generated by Django 4.0.4 on 2022-06-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
