# Generated by Django 4.0.4 on 2022-06-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetcode',
            name='reset_code',
            field=models.CharField(max_length=500),
        ),
    ]
