# Generated by Django 4.0.4 on 2022-06-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_resetcode_reset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetcode',
            name='reset_code',
            field=models.CharField(max_length=64),
        ),
    ]
